#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define BOOKERLY_11_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_11_regular.h",
  "./bookerly_11_bold.h",
  "./bookerly_11_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_12_regular.h",
  "./bookerly_12_bold.h",
  "./bookerly_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_13_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_13_regular.h",
  "./bookerly_13_bold.h",
  "./bookerly_13_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_14_regular.h",
  "./bookerly_14_bold.h",
  "./bookerly_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_15_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_15_regular.h",
  "./bookerly_15_bold.h",
  "./bookerly_15_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_16_regular.h",
  "./bookerly_16_bold.h",
  "./bookerly_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define GEORGIA_11_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./georgia_11_regular.h",
  "./georgia_11_bold.h",
  "./georgia_11_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define GEORGIA_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./georgia_12_regular.h",
  "./georgia_12_bold.h",
  "./georgia_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define GEORGIA_13_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./georgia_13_regular.h",
  "./georgia_13_bold.h",
  "./georgia_13_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define GEORGIA_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./georgia_14_regular.h",
  "./georgia_14_bold.h",
  "./georgia_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define GEORGIA_15_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./georgia_15_regular.h",
  "./georgia_15_bold.h",
  "./georgia_15_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define GEORGIA_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./georgia_16_regular.h",
  "./georgia_16_bold.h",
  "./georgia_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define VERDANA_11_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./verdana_11_regular.h",
  "./verdana_11_bold.h",
  "./verdana_11_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define VERDANA_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./verdana_12_regular.h",
  "./verdana_12_bold.h",
  "./verdana_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define VERDANA_13_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./verdana_13_regular.h",
  "./verdana_13_bold.h",
  "./verdana_13_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define VERDANA_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./verdana_14_regular.h",
  "./verdana_14_bold.h",
  "./verdana_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define VERDANA_15_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./verdana_15_regular.h",
  "./verdana_15_bold.h",
  "./verdana_15_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define VERDANA_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./verdana_16_regular.h",
  "./verdana_16_bold.h",
  "./verdana_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define MERRIWEATHER_11_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./merriweather_11_regular.h",
  "./merriweather_11_bold.h",
  "./merriweather_11_bolditalic.h",
  "./merriweather_11_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define MERRIWEATHER_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./merriweather_12_regular.h",
  "./merriweather_12_bold.h",
  "./merriweather_12_bolditalic.h",
  "./merriweather_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define MERRIWEATHER_13_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./merriweather_13_regular.h",
  "./merriweather_13_bold.h",
  "./merriweather_13_bolditalic.h",
  "./merriweather_13_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define MERRIWEATHER_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./merriweather_14_regular.h",
  "./merriweather_14_bold.h",
  "./merriweather_14_bolditalic.h",
  "./merriweather_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define MERRIWEATHER_15_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./merriweather_15_regular.h",
  "./merriweather_15_bold.h",
  "./merriweather_15_bolditalic.h",
  "./merriweather_15_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define MERRIWEATHER_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./merriweather_16_regular.h",
  "./merriweather_16_bold.h",
  "./merriweather_16_bolditalic.h",
  "./merriweather_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_10_regular.h",
  "./ubuntu_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_12_regular.h",
  "./ubuntu_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"
