#pragma once

#include <builtinFonts/bookerly_12_bold.h>
#include <builtinFonts/bookerly_12_italic.h>
#include <builtinFonts/bookerly_12_regular.h>
#include <builtinFonts/bookerly_13_bold.h>
#include <builtinFonts/bookerly_13_italic.h>
#include <builtinFonts/bookerly_13_regular.h>
#include <builtinFonts/bookerly_14_bold.h>
#include <builtinFonts/bookerly_14_italic.h>
#include <builtinFonts/bookerly_14_regular.h>
#include <builtinFonts/bookerly_15_bold.h>
#include <builtinFonts/bookerly_15_italic.h>
#include <builtinFonts/bookerly_15_regular.h>
#include <builtinFonts/bookerly_16_bold.h>
#include <builtinFonts/bookerly_16_italic.h>
#include <builtinFonts/bookerly_16_regular.h>
#include <builtinFonts/cozette_10.h>
#include <builtinFonts/cozette_12.h>
#include <builtinFonts/cozette_14.h>
#include <builtinFonts/georgia_12_bold.h>
#include <builtinFonts/georgia_12_italic.h>
#include <builtinFonts/georgia_12_regular.h>
#include <builtinFonts/georgia_13_bold.h>
#include <builtinFonts/georgia_13_italic.h>
#include <builtinFonts/georgia_13_regular.h>
#include <builtinFonts/georgia_14_bold.h>
#include <builtinFonts/georgia_14_italic.h>
#include <builtinFonts/georgia_14_regular.h>
#include <builtinFonts/georgia_15_bold.h>
#include <builtinFonts/georgia_15_italic.h>
#include <builtinFonts/georgia_15_regular.h>
#include <builtinFonts/georgia_16_bold.h>
#include <builtinFonts/georgia_16_italic.h>
#include <builtinFonts/georgia_16_regular.h>
#include <builtinFonts/merriweather_12_bold.h>
#include <builtinFonts/merriweather_12_bolditalic.h>
#include <builtinFonts/merriweather_12_italic.h>
#include <builtinFonts/merriweather_12_regular.h>
#include <builtinFonts/merriweather_13_bold.h>
#include <builtinFonts/merriweather_13_bolditalic.h>
#include <builtinFonts/merriweather_13_italic.h>
#include <builtinFonts/merriweather_13_regular.h>
#include <builtinFonts/merriweather_14_bold.h>
#include <builtinFonts/merriweather_14_bolditalic.h>
#include <builtinFonts/merriweather_14_italic.h>
#include <builtinFonts/merriweather_14_regular.h>
#include <builtinFonts/merriweather_15_bold.h>
#include <builtinFonts/merriweather_15_bolditalic.h>
#include <builtinFonts/merriweather_15_italic.h>
#include <builtinFonts/merriweather_15_regular.h>
#include <builtinFonts/merriweather_16_bold.h>
#include <builtinFonts/merriweather_16_bolditalic.h>
#include <builtinFonts/merriweather_16_italic.h>
#include <builtinFonts/merriweather_16_regular.h>
#include <builtinFonts/verdana_12_bold.h>
#include <builtinFonts/verdana_12_italic.h>
#include <builtinFonts/verdana_12_regular.h>
#include <builtinFonts/verdana_13_bold.h>
#include <builtinFonts/verdana_13_italic.h>
#include <builtinFonts/verdana_13_regular.h>
#include <builtinFonts/verdana_14_bold.h>
#include <builtinFonts/verdana_14_italic.h>
#include <builtinFonts/verdana_14_regular.h>
#include <builtinFonts/verdana_15_bold.h>
#include <builtinFonts/verdana_15_italic.h>
#include <builtinFonts/verdana_15_regular.h>
#include <builtinFonts/verdana_16_bold.h>
#include <builtinFonts/verdana_16_italic.h>
#include <builtinFonts/verdana_16_regular.h>
