#pragma once

#include <builtinFonts/vollkorn_12_bold.h>
#include <builtinFonts/vollkorn_12_bolditalic.h>
#include <builtinFonts/vollkorn_12_italic.h>
#include <builtinFonts/vollkorn_12_regular.h>
#include <builtinFonts/vollkorn_14_bold.h>
#include <builtinFonts/vollkorn_14_bolditalic.h>
#include <builtinFonts/vollkorn_14_italic.h>
#include <builtinFonts/vollkorn_14_regular.h>
#include <builtinFonts/vollkorn_16_bold.h>
#include <builtinFonts/vollkorn_16_bolditalic.h>
#include <builtinFonts/vollkorn_16_italic.h>
#include <builtinFonts/vollkorn_16_regular.h>
#include <builtinFonts/vollkorn_18_bold.h>
#include <builtinFonts/vollkorn_18_bolditalic.h>
#include <builtinFonts/vollkorn_18_italic.h>
#include <builtinFonts/vollkorn_18_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/cozette_10_bold.h>
#include <builtinFonts/cozette_10_regular.h>
#include <builtinFonts/cozette_12_bold.h>
#include <builtinFonts/cozette_12_regular.h>
#include <builtinFonts/cozette_14_bold.h>
#include <builtinFonts/cozette_14_regular.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_regular.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_regular.h>
#include <builtinFonts/ubuntu_14_bold.h>
#include <builtinFonts/ubuntu_14_regular.h>
