#pragma once

#include <builtinFonts/bookerly_12_bold.h>
#include <builtinFonts/bookerly_12_italic.h>
#include <builtinFonts/bookerly_12_regular.h>
#include <builtinFonts/bookerly_13_bold.h>
#include <builtinFonts/bookerly_13_italic.h>
#include <builtinFonts/bookerly_13_regular.h>
#include <builtinFonts/bookerly_14_bold.h>
#include <builtinFonts/bookerly_14_italic.h>
#include <builtinFonts/bookerly_14_regular.h>
#include <builtinFonts/bookerly_15_bold.h>
#include <builtinFonts/bookerly_15_italic.h>
#include <builtinFonts/bookerly_15_regular.h>
#include <builtinFonts/bookerly_16_bold.h>
#include <builtinFonts/bookerly_16_italic.h>
#include <builtinFonts/bookerly_16_regular.h>
#include <builtinFonts/cozette_10.h>
#include <builtinFonts/cozette_12.h>
#include <builtinFonts/cozette_14.h>
