"""
PlatformIO pre-build script: give the tickless-idle FreeRTOS functions a home in
the linker script.

Why this exists
---------------
`custom_sdkconfig` in platformio.ini turns on CONFIG_FREERTOS_USE_TICKLESS_IDLE.
pioarduino honours that when it rebuilds the IDF libraries and when it
regenerates `ld/memory.ld`, but it does NOT regenerate `ld/sections.ld` -- that
file ships prebuilt in framework-arduinoespressif32-libs, produced by ldgen
against the stock sdkconfig in which tickless idle is off.

components/freertos/linker.lf has two `if FREERTOS_USE_TICKLESS_IDLE = y:`
branches (lines 195 and 267 in ESP-IDF 5.5) that place three symbols. With
tickless idle off those branches are not emitted, so the prebuilt sections.ld
lists neither them nor any catch-all that would take them: the generic
`*libfreertos.a:` rule explicitly EXCLUDE_FILEs `tasks.*`, and the `tasks.*`
rules are enumerated symbol by symbol.

Turning tickless idle on therefore produces object code that no rule claims.
The linker drops it into orphan output sections just past `_text_end`, and the
build fails at image packing with:

    A fatal error occurred: Invalid .text.prvGetExpectedIdleTime segment
    length 0x11bf2. It has to be multiple of 4.

The alignment complaint is the symptom. The real problem is placement: these
run on the light-sleep entry and wake path, which is exactly the path
CONFIG_PM_SLP_IRAM_OPT=y exists to keep out of flash. They belong in IRAM
alongside the rest of their block in linker.lf, which is where this script puts
them.

What it does
------------
Appends one input-section rule to the existing `*libfreertos.a:tasks.*` line
inside the `.iram0.text` output section, naming the three symbols and nothing
else. Named rather than a `.text.*` sweep on purpose: sections.ld deliberately
keeps `uxTaskGetSnapshotAll` and `xTaskGetNext` from the same object in
`.flash.text`, and a sweep here would pull them into IRAM -- which on the C3
comes out of the same SRAM pool as the heap.

Idempotent via a marker comment, and re-run on every build because the package
directory it edits is regenerated by the custom_sdkconfig rebuild.

The post-link check at the bottom is the runnable part. The S3 failed silently
the first time this script ran -- its sections.ld lives under `<mcu>/<flash
mode>/` instead of `<mcu>/ld/`, so the patch missed it, the symbols stayed in
flash, and the image happened to pack anyway because its length landed on a
4-byte boundary by luck. A wrong placement that only sometimes announces itself
is worth an assertion.
"""

Import("env")  # noqa: F821 (SCons-injected global)
import glob
import os
import subprocess
import sys


MARKER = "/* lector: FREERTOS_USE_TICKLESS_IDLE placement */"

# The symbols the two `if FREERTOS_USE_TICKLESS_IDLE = y:` branches in
# components/freertos/linker.lf add. `.literal.*` is dead weight on RISC-V and
# load-bearing on Xtensa; listing both keeps one rule valid for every target.
TICKLESS_SYMBOLS = (
    "prvGetExpectedIdleTime",
    "eTaskConfirmSleepModeStatus",
    "vTaskStepTick",
)

# The line the rule is appended after: the FIRST enumerated placement for
# tasks.c, which is the one inside `.iram0.text` -- that output section is
# emitted before `.flash.text` on every target. The later `tasks.*` rules
# (uxTaskGetSnapshotAll, xTaskGetNext) sit in `.flash.text` and must be left
# alone. Matched on the rule text rather than a line number so a package update
# that reorders the file fails loudly instead of patching the wrong section.
#
# The enumerations themselves differ per target (RISC-V has no `.literal.*`, so
# the C3 rule opens with `.text .text.__getreent` where the S3 opens with
# `.literal.__getreent`), which is why the anchor stops at the opening paren.
ANCHOR = "*libfreertos.a:tasks.*("


def _rule():
    patterns = " ".join(
        f".literal.{name} .text.{name}" for name in TICKLESS_SYMBOLS
    )
    return f"    {MARKER}\n    *libfreertos.a:tasks.*({patterns})\n"


def _sections_ld_paths(env):
    # Per MCU, and the layout differs between them: the C3 keeps one
    # `<mcu>/ld/sections.ld`, the S3 keeps one per flash mode
    # (`<mcu>/qio_qspi/sections.ld` and siblings). Glob rather than guess, and
    # patch every copy -- they are the same generated file and the build picks
    # its flash mode later.
    mcu = env.BoardConfig().get("build.mcu", "")
    package_dir = env.PioPlatform().get_package_dir(
        "framework-arduinoespressif32-libs"
    )
    if not mcu or not package_dir:
        return []
    return sorted(glob.glob(os.path.join(package_dir, mcu, "*", "sections.ld")))


def patch_sections_ld(env):
    paths = _sections_ld_paths(env)
    if not paths:
        # No rebuilt-libs package: this build is not using custom_sdkconfig, so
        # tickless idle is not on either and there is nothing to place.
        return
    for path in paths:
        _patch_one(path)


def _patch_one(path):
    with open(path, "r") as handle:
        text = handle.read()

    if MARKER in text:
        return

    anchor_at = text.find(ANCHOR)
    if anchor_at < 0:
        sys.stderr.write(
            "ERROR: %s has no '%s' rule to anchor the tickless-idle placement "
            "to. Without it the two functions land in flash on the light-sleep "
            "wake path, and on some targets the build also fails at image "
            "packing with an unaligned orphan segment. Check "
            "components/freertos/linker.lf against the symbols in this file.\n"
            % (path, ANCHOR)
        )
        raise SystemExit(1)

    line_end = text.index("\n", anchor_at) + 1
    with open(path, "w") as handle:
        handle.write(text[:line_end] + _rule() + text[line_end:])
    print("Placed tickless-idle FreeRTOS symbols in IRAM: %s" % path)


# IRAM is 0x403xxxxx on both the C3 and the S3; flash-mapped instructions are
# 0x42xxxxxx. One nibble tells the two apart.
IRAM_PREFIX = 0x403


def check_tickless_placement(source, target, env):
    """Fail the build if a tickless symbol was left in flash."""
    elf = str(target[0])
    nm = env.subst("$CC").replace("-gcc", "-nm")
    try:
        out = subprocess.run(
            [nm, elf], capture_output=True, text=True, check=True
        ).stdout
    except (OSError, subprocess.CalledProcessError) as exc:
        sys.stderr.write("WARNING: tickless placement not checked: %s\n" % exc)
        return

    addresses = {}
    for line in out.splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[2] in TICKLESS_SYMBOLS:
            addresses[parts[2]] = int(parts[0], 16)

    if not addresses:
        # Tickless idle is off in this build; nothing was meant to move.
        return

    stranded = {
        name: addr
        for name, addr in addresses.items()
        if addr >> 20 != IRAM_PREFIX
    }
    if stranded:
        sys.stderr.write(
            "ERROR: tickless-idle symbols left in flash: %s\n"
            "They run on the light-sleep entry and wake path and must be in "
            "IRAM. The sections.ld patch in this script did not reach the "
            "linker script this environment used.\n"
            % ", ".join("%s at 0x%08x" % kv for kv in sorted(stranded.items()))
        )
        raise SystemExit(1)
    print(
        "Tickless-idle symbols in IRAM: %s"
        % ", ".join(sorted(addresses))
    )


patch_sections_ld(env)  # noqa: F821
env.AddPostAction("$BUILD_DIR/${PROGNAME}.elf", check_tickless_placement)  # noqa: F821
