#pragma once

#include <Icon.h>

#include <cstdint>

// The light panel's brightness row marker, 24x24 with a 2 px stroke. Drawn here rather than
// converted from an SVG: the icon set's own generator needs cairosvg, and these two shapes
// are simple enough to be their own source.
//
// Stored quarter-turned, like every other asset drawIcon takes — see skull12.h. The art
// below is the screen-space picture, which is what to edit against.
//   ...........##...........
//   ...........##...........
//   ...........##...........
//   ...##..............##...
//   ....##............##....
//   .....##..........##.....
//   ........................
//   ..........####..........
//   ........########........
//   ........##....##........
//   .......##......##.......
//   ###....##......##....###
//   ###....##......##....###
//   .......##......##.......
//   ........##....##........
//   ........########........
//   ..........####..........
//   ........................
//   .....##..........##.....
//   ....##............##....
//   ...##..............##...
//   ...........##...........
//   ...........##...........
//   ...........##...........
static constexpr uint8_t Sun24IconBits[] = {
    0xFF, 0xE7, 0xFF, 0xFF, 0xE7, 0xFF, 0xFF, 0xE7, 0xFF, 0xEF, 0xFF, 0xF7, 0xE7, 0xFF, 0xE7, 0xF3, 0xFF, 0xCF,
    0xFB, 0xFF, 0xDF, 0xFF, 0xC3, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0x3C, 0xFF, 0xFE, 0x7E, 0x7F, 0x1E, 0x7E, 0x78,
    0x1E, 0x7E, 0x78, 0xFE, 0x7E, 0x7F, 0xFF, 0x3C, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xC3, 0xFF, 0xFB, 0xFF, 0xDF,
    0xF3, 0xFF, 0xCF, 0xE7, 0xFF, 0xE7, 0xEF, 0xFF, 0xF7, 0xFF, 0xE7, 0xFF, 0xFF, 0xE7, 0xFF, 0xFF, 0xE7, 0xFF};
static const freeink::Icon Sun24Icon = {24, 24, 12, Sun24IconBits};
