#pragma once

#include <Icon.h>

#include <cstdint>

// The light panel's warmth row marker, 24x24 with a 2 px stroke. Drawn here rather than
// converted from an SVG: the icon set's own generator needs cairosvg, and these two shapes
// are simple enough to be their own source.
//
// Stored quarter-turned, like every other asset drawIcon takes — see skull12.h. The art
// below is the screen-space picture, which is what to edit against.
//   ........................
//   ........................
//   .........######.........
//   ........##....##........
//   ........##....##........
//   ........##....##........
//   ........##....##........
//   ........##....##........
//   ........##....##........
//   ........##....##........
//   ........##....##........
//   ........##....##........
//   ........##....##........
//   .......##......##.......
//   ......##........##......
//   ......##........##......
//   .....##..........##.....
//   .....##..........##.....
//   .....##..........##.....
//   ......##........##......
//   ......##........##......
//   .......##......##.......
//   ........########........
//   ........................
static constexpr uint8_t Thermometer24IconBits[] = {
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x1F,
    0xFF, 0xFC, 0x07, 0xFF, 0xF8, 0xE3, 0xE0, 0x03, 0xF9, 0xC0, 0x07, 0xFD, 0xDF, 0xFF, 0xFD, 0xDF, 0xFF, 0xFD,
    0xDF, 0xFF, 0xFD, 0xDF, 0xFF, 0xFD, 0xC0, 0x07, 0xFD, 0xE0, 0x03, 0xF9, 0xFF, 0xF8, 0xE3, 0xFF, 0xFC, 0x07,
    0xFF, 0xFF, 0x1F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF};
static const freeink::Icon Thermometer24Icon = {24, 24, 12, Thermometer24IconBits};
