// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define CHAREINK_14_FONT_ID (75174429)
// Active UI font ids (menus/lists/hints). Bound at boot + on language change to
// either the Cozette family (default, most languages) or the Ubuntu family
// (Arabic/Hebrew fallback). The id VALUES are derived from the Cozette headers.
#define UI_10_FONT_ID (-2061243555)
#define UI_12_FONT_ID (1074320014)
// Permanent Ubuntu ids: always bound to the Ubuntu family regardless of language.
// Used by the language-select list so Arabic/Hebrew native names never box.
#define UBUNTU_10_FONT_ID (-350896663)
#define UBUNTU_12_FONT_ID (-884914451)
#define SMALL_FONT_ID (674098198)
// Contents look (the in-book menu first): Literata pinned per pixel size by
// lib/EpdFont/scripts/convert-literata-ui.py.
#define LITERATA_UI_20_FONT_ID (-99404749)
#define LITERATA_UI_26_FONT_ID (-1909874435)
#define LITERATA_UI_25_FONT_ID (952529669)
#define LITERATA_UI_16_FONT_ID (1786701152)
#define LITERATA_UI_19_SC_FONT_ID (1582423704)
#define LITERATA_UI_19_IT_FONT_ID (-1717519899)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(CHAREINK_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UBUNTU_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UBUNTU_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATA_UI_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATA_UI_26_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATA_UI_25_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATA_UI_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATA_UI_19_SC_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATA_UI_19_IT_FONT_ID != 0, "Font ID collision with sentinel");
