// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define VOLLKORN_12_FONT_ID (-406142856)
#define VOLLKORN_14_FONT_ID (-266107326)
#define VOLLKORN_16_FONT_ID (385416782)
#define VOLLKORN_18_FONT_ID (2100450296)
#define UI_10_FONT_ID (22918846)
#define UI_12_FONT_ID (1635686837)
#define SMALL_FONT_ID (674098198)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(VOLLKORN_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(VOLLKORN_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(VOLLKORN_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(VOLLKORN_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
